FROM mcr.microsoft.com/devcontainers/typescript-node:16-bullseye

RUN export DEBIAN_FRONTEND=noninteractive && apt-get update \
    && apt-get install -y libnss3 libatk-bridge2.0-0 libcups2 libdrm2 libgtk-3-0 libgbm1 libasound2
